@echo off
del CodeStats.txt

call CountLinesInFile.bat src\Applications\MultiAlign\App.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Settings.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\BaseCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\BrowseFolderCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\BrowseOpenFileCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\BrowseSaveFileCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Clusters\ClusterExportCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Datasets\ShowDatasetDetailCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Plotting\FeatureDisplayCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Plotting\PictureDisplayCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Viewers\LoadExistingAnalysisCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Viewers\LoadRecentAnalysisCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Viewers\StartNewAnalysisCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Wizard\AnalysisBackCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Wizard\AnalysisCancelCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Commands\Wizard\AnalysisNextCommand.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\AnalysisStepVisibilityConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\BooleanToDataGridVisibilityModeConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\BoolInverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\BoolListSizeConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\BoolVisibilityConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\BoolWidthConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DatasetColorConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DatasetCountConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DatasetFolderPathConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DatasetPathConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DatasetSelectedConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\DoubleToStringConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\HasPathConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\IntToStringConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\IntVisibilityConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\OrientationMsMsConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\SearchOptionConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\UriToBitmapConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\ViewStateIsSelectedConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Converters\ViewStateVisibilityConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\ApplicationStatusMediator.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\DatasetFilterFactory.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\DatasetPlotLoader.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\ImageConverter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\LogicLayerViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\MultiAlignAnalysisValidator.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\OpenAnalysisArgs.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\RecentAnalysis.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\StatusMessageWrapper.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\ThreadSafeDispatcher.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\States\AnalysisSetupState.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\States\AnalysisState.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Data\States\ViewState.cs
call CountLinesInFile.bat src\Applications\MultiAlign\IO\DatasetSearcher.cs
call CountLinesInFile.bat src\Applications\MultiAlign\IO\ManassaWorkspaceReader.cs
call CountLinesInFile.bat src\Applications\MultiAlign\IO\ManassaWorkspaceWriter.cs
call CountLinesInFile.bat src\Applications\MultiAlign\IO\SpectraLoader.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\AnalysisViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\ImageViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\MainViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\MassTagMatchedViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\PictureViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\RecentAnalysisViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\StateModeratorViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\ViewModelBase.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\MsFeatureSpectraViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\MsMsSpectraViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\PlotModelBase.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\PositionArgs.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\UmcClusterHistogram.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Charting\XicViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Databases\DatabasesViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Databases\DmsDatabaseServerViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Datasets\DatasetCollectionViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Datasets\DatasetInformationViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Datasets\DatasetResolveCollectionViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Datasets\DatasetResolveMatchViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Features\ChargeStateViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Features\SpectraSortOptions.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Features\UMCClusterFilterViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Features\UMCClusterIdentificationViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Instruments\InstrumentPresetFactory.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Instruments\InstrumentPresets.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Instruments\InstrumentPresetViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\IO\ClusterExportViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\IO\MassTagDatabaseOptionsViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Plotting\FeaturesViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Plotting\PlotDataViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Proteins\PeptideViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Proteins\ProteinViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Spectra\MSSpectraViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Spectra\UMCClusterSpectraViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\FeatureSelectedEventArgs.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\GenericCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\IdentificationCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MassTagCollectionMatchTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MassTagMatchTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MassTagToClusterMatch.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MassTagTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MsMsCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\MsMsTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\PeptideCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\PeptideTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\StatisticTreeViewItem.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\TreeItemViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\UMCClusterCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\UMCClusterTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\UMCCollectionTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\TreeView\UMCTreeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Viewers\ClusterViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Viewers\GettingStartedViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Viewers\GlobalStatisticsViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisBaselineSelectionViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisDatasetSelectionViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisGraphNodeViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisLoadingViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisNamingViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisOptionsViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisRunningViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisSetupViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\AnalysisStatusArgs.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\ExperimentPresetFactory.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\ExperimentPresets.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\ExperimentPresetViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\ViewModels\Wizard\StacOptionsViewModel.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\FilePathFinder.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\MainWindow.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Controls\AdvancedOptionsWindow.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\IO\ClusterExportView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\IO\NameDescriptionControl.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\AlignmentPlotView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\ClustersPlotView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\FeaturePlotView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\LargeFeatureView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\LargeImageView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Plots\MsSpectra.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\AnalysisView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\GettingStarted.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\GlobalStatistics.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\IdentificationView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\LoadingAnalysisView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\RangeView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\StartWindow.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterControl.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterFilterControl.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterFilterWindow.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterItemTemplate.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterOverview.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterToMassTagGrid.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\ClusterTree.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Clusters\UMCSummaryView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Databases\DatabaseSearchTool.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Databases\DatabaseSearchToolWindow.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Databases\DatabaseView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Databases\IdentificationTree.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Databases\MassTagOptionsView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Datasets\DatasetInformationView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Datasets\DatasetInputFileEditor.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Datasets\DatasetPlotView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Datasets\DatasetResolveView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Datasets\DatasetView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Features\ChargeStateControl.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Identifications\IdentificationDetail.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\MassTags\MassTagDetail.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Proteins\ProteinDetail.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Proteins\ProteinGrid.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Proteins\ProteinListBox.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Spectra\MSSpectraSummary.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Spectra\MSSpectraTemplate.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Spectra\SpectraDetail.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Viewers\Spectra\SpectraView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\AnalysisNaming.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\AnalysisRunningView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\CondensedAnalysisOptionsView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\DatasetSelection.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\PerformAnalysisControl.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\SelectBaselinesAndOptions.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Windows\Wizard\StacOptionsView.xaml.cs
call CountLinesInFile.bat src\Applications\MultiAlign\Workspace\Workspace.cs
call CountLinesInFile.bat src\Applications\MultiAlignConsole\Program.cs
call CountLinesInFile.bat src\Applications\MultiAlignConsole\IO\ClusterExporterComposite.cs
call CountLinesInFile.bat src\GridApps\MultiAlignChargeStateProcessor\Program.cs
call CountLinesInFile.bat src\GridApps\MultiAlignChargeStateProcessor\UmcClusterWriter.cs
call CountLinesInFile.bat src\GridApps\MultiAlignSTACRunner\FilteringOptions.cs
call CountLinesInFile.bat src\GridApps\MultiAlignSTACRunner\Program.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\ApplicationUtility.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\ICloneable.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AlgorithmBuilder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AlgorithmProvider.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisController.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisGraph.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisGraphBuilder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisGraphEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisGraphNode.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisStep.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\AnalysisValidator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\ClusterFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\DelegateAnalysisMethod.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeaturesClusteredEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FunctionalRedundancy.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\MultiAlignAnalysisProcessor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\PeptideMsMsLinker.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\DriftTimeAligner.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\DriftTimeAlignmentOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\DummyAlignment.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\FeatureAlignerFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\LCMSWarpFeatureAligner.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Alignment\SpectralAlignerWrapper.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Clustering\ClusteringOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Clustering\MsnClusterer.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\AbundanceReportingType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\FeatureEvaluator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\FeatureFinderFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\FeatureFinderType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\ILcmsFeatureRefinement.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\UMCFeatureFinder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\UMCFeatureFinderOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\UMCTreeFeatureFinder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\XicAdaptor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureFinding\XicFinder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureMatcher\IPeakMatcher.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureMatcher\PeakMatchingType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureMatcher\STAC.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\FeatureMatcher\TraditionalPeakMatcher.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\ClusterErrorHistograms.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\FeatureConsolidatorFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\FeatureConsolidatorOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\LCMSFeatureConsolidator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\UMCAbundanceConsolidator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Features\UMCAbundanceSumConsolidator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\MSLinker\MSLinkerOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\MSLinker\MSLinkerType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\MSLinker\MSnFeaturesExtractedEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\MSLinker\MSnLinkerFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Options\AlignmentOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Options\MassTagDatabaseOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Options\MultiAlignAnalysisOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Options\STACOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Workflow\Alignment.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Algorithms\Workflow\WorkflowBase.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\AnalysisCompleteEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\AnalysisConfig.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\AnalysisErrorEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\AnalysisOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\AnalysisUtils.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\BaselineFeaturesLoadedEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\clsDatabaseDatasetLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\clsUMCFindingOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\ClusterToMassTagMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\DataSummaryAttribute.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\FeaturesLoadedEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\FeaturesPeakMatchedEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\FilterBase.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\IFeatureMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MassTagLightCacheManager.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MassTagsLoadedEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MassTagToMatch.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MassTagToProteinMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MSFeatureToMSnFeatureMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MSMSClusterMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MultiAlignAnalysis.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MultiAlignAnalysisDelegates.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\PeakMatchingResults.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\ProteinToMassTags.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\UMCClusterLightCacheManager.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Alignment\classAlignmentData.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\DatasetToExperimentalFactorMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\ExperimentalFactor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\Factor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\FactorDefinitions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\FactorInfo.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\FactorInformation.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\FactorTree.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\TreeNode.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Factors\TreeNodeConverter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\ClusterStats.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\FeatureAnnotation.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\FeatureDataConverters.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\FeatureFilterOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\LCMSFeatureChargeMapBuilder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\MSFeatureMsMs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\UMCClusterMatched.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\Features\UMCExtended.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MassTags\MassTagDatabaseFormat.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MetaData\AnalysisMetaData.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MetaData\clsDMSServerInformation.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MetaData\DatasetInformation.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MetaData\DatasetPlotInformation.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\MetaData\SupportedDatasetType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\SequenceData\DatabaseSearchSequence.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Data\SequenceData\SequenceToMsnFeature.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\ClusterExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\DatasetInformationCollection.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\FeatureExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\GenericExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\MassTagExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\MSFeatureExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\MSSpectraExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\PeptideExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Extensions\XYDataExtensions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\CommandLineProcessor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\DataAccessFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\DatabaseIndexer.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\FeatureCache.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\IGenericDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\IMageSink.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Logger.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SingletonDataProviders.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\StatusEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Analysis\IFactorDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Analysis\PeakMatchResultsWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\BaseUmcClusterWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\ClusterExporterComposite.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\IFeatureClusterWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterAbundanceCrossTabWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterAbundanceSumCrossTabWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterCrossTabWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterExporterFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterMsmsMetaDataWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterMsmsSpectraWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Clusters\UMCClusterScanWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Datasets\IDatasetDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Datasets\IDatasetToFactorMapDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Factors\FactorFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Factors\MAGEFactorAdaptor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Factors\MultiAlignFactorSink.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\BaseLCMSFeatureReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\FeatureAdjusterWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\FeatureDataAccessProviders.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\IAlignmentDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\IMSFeatureDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\IUmcClusterDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\IUmcDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\LCMSFeatureFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\MSnFragmentationTableWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\UmcAdoDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\UMCLoaderFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\UmcLoadingEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Features\UmcReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Generic\JsonReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Generic\JsonWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\AlignmentDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\ClusterToMassTagMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\DatasetDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\DatasetToFactorMap.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\FactorDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\GenericDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MassTagDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MassTagMatchDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MSFeatureDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MSMSClusterMapDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MSnFeatureDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\MSnFeatureToMSFeatureDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\NHibernateUtil.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\ProteinDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\STACDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\UmcClusterDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Hibernate\UmcDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\CommandLineParser.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\FileCopyEventArgs.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\InputAnalysisInfo.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\InputDatabase.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\InputFile.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\InputFileReadMode.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\InputFileType.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\InputFiles\MultiAlignFileInputReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Logging\AnalysisLogWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MassTags\IMassTagDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MassTags\IMassTagMatchDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MsMs\IMSMSClusterMapDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MsMs\IMSnFeatureDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MsMs\IMSnFeatureToMSFeatureDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MsMs\MSMSClusterWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MsMs\ParentSpectraFinder.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\AnalysisMTDBSetupException.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\APEMassTagDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\DriftTimeTextFileDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\IDatabaseServerLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\IMTDBLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MageDmsDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MAGEMetaSampleDatabaseSink.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MassTagDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MassTagDatabaseLoaderCache.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MassTagDatabaseLoaderFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MassTagDatabaseOptions.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MetaSampleDatbaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MtdbCreatorDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MTDBLoaderFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MTSMassTagDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MTSPeakMatchResultsWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\MTSSqlServerPeakMatchResultWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\PeakMatchDMSWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\SqliteMassTagDatabaseLoader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\MTDB\XAMTReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\MultiAlignParameterIniFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\MultiAlignParameterIniFileWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\ParameterFileAttribute.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\ParameterFileGroupAttribute.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\ParameterHibernateMapping.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\ParameterUtility.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\xmlIO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\XMLParameterFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Parameters\XMLParameterFileWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Proteins\IProteinDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Proteins\PeptideScanWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\CachedFeatureSpectraProvider.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\IRawDataFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\MzXMLReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\RawLoaderFactory.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\ScanOutOfRangeException.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\RawData\ThermoRawDataFileReader.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Reports\AnalysisHTMLReport.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Reports\AnalysisReportGenerator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Reports\IAnalysisReportGenerator.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\DatabaseSearchSequenceDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\IDatabaseSearchSequenceDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\ISequenceToMsnFeatureDAO.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\MAGEDatabaseSearchAdaptor.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\SequenceToMsnDAOHibernate.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\SequenceData\SequestFirstHitSink.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Xic\IXicWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Xic\XicComparisonWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Xic\XicFitWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Xic\XicMsFeatureWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\IO\Xic\XicWriter.cs
call CountLinesInFile.bat src\Library\MultiAlignCore\Math\MathUtilities.cs

pause
