//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiAlignWin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\")]
        public string RawDataPath {
            get {
                return ((string)(this["RawDataPath"]));
            }
            set {
                this["RawDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caulo_049_[2-4]")]
        public string DMSDataSetRegularExpression {
            get {
                return ((string)(this["DMSDataSetRegularExpression"]));
            }
            set {
                this["DMSDataSetRegularExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DMSConnectionTimeout {
            get {
                return ((int)(this["DMSConnectionTimeout"]));
            }
            set {
                this["DMSConnectionTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gigasax")]
        public string DMSServerName {
            get {
                return ((string)(this["DMSServerName"]));
            }
            set {
                this["DMSServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DMS5")]
        public string DMSDatabaseName {
            get {
                return ((string)(this["DMSDatabaseName"]));
            }
            set {
                this["DMSDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentMassTagDatabases {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentMassTagDatabases"]));
            }
            set {
                this["RecentMassTagDatabases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double UserPeakPickingMonoMass {
            get {
                return ((double)(this["UserPeakPickingMonoMass"]));
            }
            set {
                this["UserPeakPickingMonoMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double UserPeakPickingAverageMass {
            get {
                return ((double)(this["UserPeakPickingAverageMass"]));
            }
            set {
                this["UserPeakPickingAverageMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double UserPeakPickingLogAbundance {
            get {
                return ((double)(this["UserPeakPickingLogAbundance"]));
            }
            set {
                this["UserPeakPickingLogAbundance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double UserPeakPickingScan {
            get {
                return ((double)(this["UserPeakPickingScan"]));
            }
            set {
                this["UserPeakPickingScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double UserPeakPickingNet {
            get {
                return ((double)(this["UserPeakPickingNet"]));
            }
            set {
                this["UserPeakPickingNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserPeakPickingUseNet {
            get {
                return ((bool)(this["UserPeakPickingUseNet"]));
            }
            set {
                this["UserPeakPickingUseNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double UserPeakPickingFit {
            get {
                return ((double)(this["UserPeakPickingFit"]));
            }
            set {
                this["UserPeakPickingFit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double UserPeakPickingMaxDist {
            get {
                return ((double)(this["UserPeakPickingMaxDist"]));
            }
            set {
                this["UserPeakPickingMaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double UserPeakPickingMinDist {
            get {
                return ((double)(this["UserPeakPickingMinDist"]));
            }
            set {
                this["UserPeakPickingMinDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double UserPeakPickingMonoMassConstraintPPM {
            get {
                return ((double)(this["UserPeakPickingMonoMassConstraintPPM"]));
            }
            set {
                this["UserPeakPickingMonoMassConstraintPPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double UserPeakPickingAverageMassConstraintPPM {
            get {
                return ((double)(this["UserPeakPickingAverageMassConstraintPPM"]));
            }
            set {
                this["UserPeakPickingAverageMassConstraintPPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caulo_049_[2-4]")]
        public string UserDataLoaderRegEx {
            get {
                return ((string)(this["UserDataLoaderRegEx"]));
            }
            set {
                this["UserDataLoaderRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double UserClusterOptionsMassTolerance {
            get {
                return ((double)(this["UserClusterOptionsMassTolerance"]));
            }
            set {
                this["UserClusterOptionsMassTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserClusterOptionsUseMaxInDataset {
            get {
                return ((bool)(this["UserClusterOptionsUseMaxInDataset"]));
            }
            set {
                this["UserClusterOptionsUseMaxInDataset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double UserClusterOptionsNETTolerance {
            get {
                return ((double)(this["UserClusterOptionsNETTolerance"]));
            }
            set {
                this["UserClusterOptionsNETTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserClusterOptionsUseMeanRepresentation {
            get {
                return ((bool)(this["UserClusterOptionsUseMeanRepresentation"]));
            }
            set {
                this["UserClusterOptionsUseMeanRepresentation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAlignmentOptionsCalibrationTypeMzCoeff {
            get {
                return ((bool)(this["UserAlignmentOptionsCalibrationTypeMzCoeff"]));
            }
            set {
                this["UserAlignmentOptionsCalibrationTypeMzCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserAlignmentOptionsCalibrationTypeNetRelationship {
            get {
                return ((bool)(this["UserAlignmentOptionsCalibrationTypeNetRelationship"]));
            }
            set {
                this["UserAlignmentOptionsCalibrationTypeNetRelationship"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAlignmentOptionsCalibrationTypeHybrid {
            get {
                return ((bool)(this["UserAlignmentOptionsCalibrationTypeHybrid"]));
            }
            set {
                this["UserAlignmentOptionsCalibrationTypeHybrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAlignmentOptionsUseRecalibrateMasses {
            get {
                return ((bool)(this["UserAlignmentOptionsUseRecalibrateMasses"]));
            }
            set {
                this["UserAlignmentOptionsUseRecalibrateMasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double UserAlignmentOptionsNETTolerance {
            get {
                return ((double)(this["UserAlignmentOptionsNETTolerance"]));
            }
            set {
                this["UserAlignmentOptionsNETTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int UserAlignmentOptionsNumSections {
            get {
                return ((int)(this["UserAlignmentOptionsNumSections"]));
            }
            set {
                this["UserAlignmentOptionsNumSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double UserAlignmentOptionsMaxDistortion {
            get {
                return ((double)(this["UserAlignmentOptionsMaxDistortion"]));
            }
            set {
                this["UserAlignmentOptionsMaxDistortion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double UserAlignmentOptionsContractionFactor {
            get {
                return ((double)(this["UserAlignmentOptionsContractionFactor"]));
            }
            set {
                this["UserAlignmentOptionsContractionFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double UserAlignmentOptionsMaxPromiscuity {
            get {
                return ((double)(this["UserAlignmentOptionsMaxPromiscuity"]));
            }
            set {
                this["UserAlignmentOptionsMaxPromiscuity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAlignmentOptionsIgnorePromiscuity {
            get {
                return ((bool)(this["UserAlignmentOptionsIgnorePromiscuity"]));
            }
            set {
                this["UserAlignmentOptionsIgnorePromiscuity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double UserAlignmentOptionsMassWindowPPM {
            get {
                return ((double)(this["UserAlignmentOptionsMassWindowPPM"]));
            }
            set {
                this["UserAlignmentOptionsMassWindowPPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int UserAlignmentOptionsNumMassDeltaBins {
            get {
                return ((int)(this["UserAlignmentOptionsNumMassDeltaBins"]));
            }
            set {
                this["UserAlignmentOptionsNumMassDeltaBins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int UserAlignmentOptionsNumXSlices {
            get {
                return ((int)(this["UserAlignmentOptionsNumXSlices"]));
            }
            set {
                this["UserAlignmentOptionsNumXSlices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double UserAlignmentOptionsOutlierZScore {
            get {
                return ((double)(this["UserAlignmentOptionsOutlierZScore"]));
            }
            set {
                this["UserAlignmentOptionsOutlierZScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double UserAlignmentOptionsMaxJump {
            get {
                return ((double)(this["UserAlignmentOptionsMaxJump"]));
            }
            set {
                this["UserAlignmentOptionsMaxJump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAlignmentOptionsUseLSQFit {
            get {
                return ((bool)(this["UserAlignmentOptionsUseLSQFit"]));
            }
            set {
                this["UserAlignmentOptionsUseLSQFit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int UserAlignmentOptionsLSQNumOptions {
            get {
                return ((int)(this["UserAlignmentOptionsLSQNumOptions"]));
            }
            set {
                this["UserAlignmentOptionsLSQNumOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double UserAlignmentOptionsLSQOutlierZScore {
            get {
                return ((double)(this["UserAlignmentOptionsLSQOutlierZScore"]));
            }
            set {
                this["UserAlignmentOptionsLSQOutlierZScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double UserAlignmentOptionsMassTolerance {
            get {
                return ((double)(this["UserAlignmentOptionsMassTolerance"]));
            }
            set {
                this["UserAlignmentOptionsMassTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDBFormLocalDatabasePath {
            get {
                return ((string)(this["UserDBFormLocalDatabasePath"]));
            }
            set {
                this["UserDBFormLocalDatabasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double UserDBFormPMTQuality {
            get {
                return ((double)(this["UserDBFormPMTQuality"]));
            }
            set {
                this["UserDBFormPMTQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double UserDBFormMinXCorr {
            get {
                return ((double)(this["UserDBFormMinXCorr"]));
            }
            set {
                this["UserDBFormMinXCorr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UserDBFormMinDiscriminant {
            get {
                return ((double)(this["UserDBFormMinDiscriminant"]));
            }
            set {
                this["UserDBFormMinDiscriminant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double UserDBFormPeptideProphetProbability {
            get {
                return ((double)(this["UserDBFormPeptideProphetProbability"]));
            }
            set {
                this["UserDBFormPeptideProphetProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserDBFormIncludeUnusedDBs {
            get {
                return ((bool)(this["UserDBFormIncludeUnusedDBs"]));
            }
            set {
                this["UserDBFormIncludeUnusedDBs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPeakPickingUseIntensity {
            get {
                return ((bool)(this["UserPeakPickingUseIntensity"]));
            }
            set {
                this["UserPeakPickingUseIntensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UserPeakPickingIntensityFilter {
            get {
                return ((int)(this["UserPeakPickingIntensityFilter"]));
            }
            set {
                this["UserPeakPickingIntensityFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double UserPeakPickingFitFilter {
            get {
                return ((double)(this["UserPeakPickingFitFilter"]));
            }
            set {
                this["UserPeakPickingFitFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPeakPickingInvertFitFilter {
            get {
                return ((bool)(this["UserPeakPickingInvertFitFilter"]));
            }
            set {
                this["UserPeakPickingInvertFitFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPeakPickingUseFitFilter {
            get {
                return ((bool)(this["UserPeakPickingUseFitFilter"]));
            }
            set {
                this["UserPeakPickingUseFitFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MAFirstTime {
            get {
                return ((bool)(this["MAFirstTime"]));
            }
            set {
                this["MAFirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserOutputPath {
            get {
                return ((string)(this["UserOutputPath"]));
            }
            set {
                this["UserOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPeakPickingUMCReportingTypePeakArea {
            get {
                return ((bool)(this["UserPeakPickingUMCReportingTypePeakArea"]));
            }
            set {
                this["UserPeakPickingUMCReportingTypePeakArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double UserAlignmentOptionsMassBinSize {
            get {
                return ((double)(this["UserAlignmentOptionsMassBinSize"]));
            }
            set {
                this["UserAlignmentOptionsMassBinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double UserAlignmentOptionsNETBinSize {
            get {
                return ((double)(this["UserAlignmentOptionsNETBinSize"]));
            }
            set {
                this["UserAlignmentOptionsNETBinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double UserClusterOptionsDriftTimeTolerance {
            get {
                return ((double)(this["UserClusterOptionsDriftTimeTolerance"]));
            }
            set {
                this["UserClusterOptionsDriftTimeTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMARTIsDataPaired {
            get {
                return ((bool)(this["SMARTIsDataPaired"]));
            }
            set {
                this["SMARTIsDataPaired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double SMARTNETTolerance {
            get {
                return ((double)(this["SMARTNETTolerance"]));
            }
            set {
                this["SMARTNETTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SMARTMassTolerance {
            get {
                return ((double)(this["SMARTMassTolerance"]));
            }
            set {
                this["SMARTMassTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMARTUsePriorProbabilities {
            get {
                return ((bool)(this["SMARTUsePriorProbabilities"]));
            }
            set {
                this["SMARTUsePriorProbabilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SMARTPairedMass {
            get {
                return ((double)(this["SMARTPairedMass"]));
            }
            set {
                this["SMARTPairedMass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDBFormMTDBExperimentFilter {
            get {
                return ((string)(this["UserDBFormMTDBExperimentFilter"]));
            }
            set {
                this["UserDBFormMTDBExperimentFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDBFormMTDBPriorProbabilities {
            get {
                return ((string)(this["UserDBFormMTDBPriorProbabilities"]));
            }
            set {
                this["UserDBFormMTDBPriorProbabilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDBFormExperimentFilter {
            get {
                return ((string)(this["UserDBFormExperimentFilter"]));
            }
            set {
                this["UserDBFormExperimentFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDBFormExperimentExclusionFilter {
            get {
                return ((string)(this["UserDBFormExperimentExclusionFilter"]));
            }
            set {
                this["UserDBFormExperimentExclusionFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03")]
        public double UserPeakMatchingNETTolerance {
            get {
                return ((double)(this["UserPeakMatchingNETTolerance"]));
            }
            set {
                this["UserPeakMatchingNETTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double UserPeakMatchingMassTolerance {
            get {
                return ((double)(this["UserPeakMatchingMassTolerance"]));
            }
            set {
                this["UserPeakMatchingMassTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double UserPeakMatchingDriftTimeTolerance {
            get {
                return ((double)(this["UserPeakMatchingDriftTimeTolerance"]));
            }
            set {
                this["UserPeakMatchingDriftTimeTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UserDBFormMinObservationCountFilter {
            get {
                return ((int)(this["UserDBFormMinObservationCountFilter"]));
            }
            set {
                this["UserDBFormMinObservationCountFilter"] = value;
            }
        }
    }
}
